# Generated by Django 5.1.1 on 2024-09-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_options_remove_profile_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='expiration_date',
            field=models.DateField(blank=True, help_text='Дата истечения тарифа', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tariff_months',
            field=models.PositiveIntegerField(default=0, help_text='Количество месяцев тарифа'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tariff_years',
            field=models.PositiveIntegerField(default=0, help_text='Количество лет тарифа'),
        ),
    ]
