# Generated by Django 5.1.1 on 2024-09-26 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_expiration_date_profile_tariff_months_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tariff_months',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tariff_years',
        ),
    ]
