# Generated by Django 4.2.11 on 2024-06-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_entry',
            field=models.DateField(blank=True, null=True, verbose_name='Дата Ввода'),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_issued',
            field=models.DateField(blank=True, null=True, verbose_name='Дата Выпуска'),
        ),
        migrations.AlterField(
            model_name='device',
            name='date_next_verification',
            field=models.DateField(blank=True, null=True, verbose_name='Дата Следующей Поверки'),
        ),
    ]
