# Generated by Django 5.1.1 on 2024-09-25 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_alter_device_date_entry_alter_device_date_issued_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='date_verification',
            field=models.DateField(blank=True, null=True, verbose_name='Дата Поверки'),
        ),
    ]
